apiVersion: apps/v1
kind: Deployment
metadata:
  name: underwater-app-jenkins 
  labels:
    app: octopus-underwater-app
spec:
  selector:
    matchLabels:
        app: octopus-underwater-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: octopus-underwater-app
    spec:
      containers:
        - name: octopus-underwater-app
          image: 008198925939.dkr.ecr.ap-south-1.amazonaws.com/octo_k8:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
